<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-JC2CKGE" failures="3" tests="4" name="Test" time="21.112" errors="0" timestamp="2021-03-01T21:44:31 IST">
  <testcase classname="TestCases.Add_Update_Pet_Request" name="addPetRequest" time="8.715">
    <failure type="java.lang.AssertionError" message="expected [809] but found [808]">
      <![CDATA[java.lang.AssertionError: expected [809] but found [808]
at TestCases.Add_Update_Pet_Request.addPetRequest(Add_Update_Pet_Request.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- addPetRequest -->
  <testcase classname="TestCases.Add_Update_Pet_Request" name="deletPetRequest" time="6.939">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
at TestCases.Add_Update_Pet_Request.deletPetRequest(Add_Update_Pet_Request.java:117)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- deletPetRequest -->
  <testcase classname="TestCases.Add_Update_Pet_Request" name="updatePetRequest" time="3.93"/>
  <testcase classname="TestCases.DeletePetRequest" name="deletPetRequest" time="1.301">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;io.restassured.response.Response.then()&amp;quot; because &amp;quot;this.response&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "io.restassured.response.Response.then()" because "this.response" is null
at TestCases.DeletePetRequest.deletPetRequest(DeletePetRequest.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- deletPetRequest -->
</testsuite> <!-- Test -->
